// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server;

namespace Server.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20201126104731_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Server.BlobPicture", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Pixels")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("BlobPictures");
                });

            modelBuilder.Entity("Server.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .HasColumnType("TEXT");

                    b.Property<int>("Label")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Server.BlobPicture", b =>
                {
                    b.HasOne("Server.Picture", "Picture")
                        .WithOne("Blob")
                        .HasForeignKey("Server.BlobPicture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Server.Picture", b =>
                {
                    b.Navigation("Blob");
                });
#pragma warning restore 612, 618
        }
    }
}
